development:
  forest_env_secret: c78bf1fc03c18147e884a22a49500e632eab56d9265855e8ce1f6a3ad7ac72f3
  forest_auth_secret: BCOXxh1btJKpNqTCQd0A1Q
staging:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
production:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
